// Define word categories
const categories = {
    subject: [
        "Apple",
        "Lime",
        "Lemon",
        "Strawberry",
        "Mango",
        "Blueberry",
        "Grape",
        "Coffee",
        "Pineapple",
        "Milk",
        "Buuter",
        "Sakura",
        "Downy",
        "Ocean Fresh",
        "Blue Fresh",
        "Aqua Fresh",
        "Acacia",
        "Lily",
        "Molto",
        "Rose",
        "Lily Splash",
        "Laundry",
        "Laundromat",
        "Laundry Room",
        "Jakarta Street,
        "National Monument Monas",
        "Ragunan Zoo",
        "Bogor Royal Garden",
        "Puncak Mountain Peak",
        "Jakarta Presidential Palace",
        "Borobudur Temple",
        "Jakarta Drown By Water Sea",
        "Flood In Bekasi City",
        "Slamet Mountain",
        "Indonesia In Dark Era",
        "Laundry Basket",
        "Beutiful Woman With Orange Hijab",
        "Handsome Man With Small Moustache",
        "Royal Blue Tshirt",
        "Orange Basketball Cap",
        "Laundry Service",
        "Laundry Application",
        "Banana",
        "Guitar",
        "Sailboat",
        "Mountains",
        "Beach",
        "Lighthouse",
        "Cityscape",
        "Eiffel Tower",
        "Flowers",
        "Sunset",
        "Waterfall",
        "Bicycle",
        "Cats",
        "Dogs",
        "Ocean Waves",
        "Desert",
        "Birds",
        "Statue",
        "Bridge",
        "Butterflies",
        "Hot Air Balloon",
        "Horses",
        "Rainforest",
        "Canyon",
        "Lakeside",
        "Rose",
        "Castle",
        "Palm Trees",
        "Old Barn",
        "Farmhouse",
        "Train",
        "Lemons",
        "Ancient Ruins",
        "Church",
        "Carousel",
        "Red Poppies",
        "Elephant",
        "Dolphin",
        "Seashells",
        "Tropical Fish",
        "Sculpture",
        "Meadow",
        "Mansion",
        "Antique Car",
        "Mushrooms",
        "Leaves",
        "Sushi",
        "Dragonfly",
        "Lily",
        "Peacock",
        "Rowboat",
        "Rainbow",
        "Book",
        "Old Bridge",
        "Acoustic Guitar",
        "Snowy Mountains",
        "Countryside",
        "Tractor",
        "Vintage Camera",
        "Seagulls",
        "Violin",
        "Water Lily",
        "Peonies",
        "Maple Trees",
        "Mandolin",
        "Sunflowers",
        "Teacup",
        "Mountain Cabin",
        "Steampunk Goggles",
        "Saxophone",
        "Ferris Wheel",
        "Panda",
        "Fox",
        "Cliffs",
        "Water Tower",
        "Bonsai Tree",
        "Amphitheater",
        "Wine Bottles",
        "Coffee Cup",
        "Rustic Barn",
        "Leather Boots",
        "Bicycle Wheel",
        "Globe",
        "Bamboo Forest",
        "Windmill",
        "Jellyfish",
        "Owl",
        "Red Kite",
        "Elephant Family",
        "Vintage Radio",
        "Row of Books",
        "Polar Bear",
        "Bulldog",
        "Motorcycle",
        "Library",
        "Sailor's Knots",
        "Clownfish",
        "Toadstools",
        "Sandcastle",
        "Victorian House",
        "Venetian Mask",
        "Vintage Suitcase",
        "Pocket Watch",
        "Cowboy Boots",
        "Tapestry",
        "Cactus",
        "Toucan",
        "Hot Rod",
        "Loose Keys",
        "Map",
        "Cafe",
        "Elephant Head",
        "Hiking Boots",
        "Fountain Pen",
        "Conch Shell",
      ],
    medium: [
        "Oil Paint",
        "Acrylic Paint",
        "Watercolor",
        "Gouache",
        "Tempera",
        "Ink",
        "Charcoal",
        "Pencil",
        "Colored Pencils",
        "Pastels (Soft and Oil)",
        "Chalk",
        "Graphite",
        "Pen and Ink",
        "Markers",
        "Digital Painting",
        "Spray Paint",
        "Collage",
        "Mixed Media",
        "Printmaking",
        "Sculpture",
        "Ceramics",
        "Pottery",
        "Wood Carving",
        "Metalwork",
        "Glassblowing",
        "Mosaic",
        "Textiles",
        "Fabric Art",
        "Batik",
        "Leatherwork",
        "Encaustic",
        "Papercraft",
        "Calligraphy",
        "Graffiti",
        "Sand Art",
        "Glitter Art",
        "Resin Art",
        "Airbrush",
        "Pencil Crayon",
        "String Art",
        "Found Objects",
        "Woodcut",
        "Linocut",
        "Papier-Mâché",
        "Stained Glass",
        "Assemblage",
        "Clay Sculpture",
        "Plaster Cast",
        "Digital Collage",
      ],
    style: [
        "Abstract Art",
        "Abstract Expressionism",
        "Art Deco",
        "Art Nouveau",
        "Baroque",
        "Byzantine Art",
        "Cubism",
        "Dadaism",
        "Digital Art",
        "Expressionism",
        "Fauvism",
        "Folk Art",
        "Gothic Art",
        "Graffiti Art",
        "Impressionism",
        "Land Art",
        "Mannerism",
        "Minimalism",
        "Naturalism",
        "Neoclassicism",
        "Op Art",
        "Orientalism",
        "Outsider Art",
        "Pop Art",
        "Post-Impressionism",
        "Pre-Raphaelite Brotherhood",
        "Realism",
        "Renaissance Art",
        "Rococo",
        "Romanticism",
        "Street Art",
        "Surrealism",
        "Symbolism",
        "Abstract Illusionism",
        "Action Painting",
        "Analytical Cubism",
        "Appropriation Art",
        "Arte Povera",
        "Ashcan School",
        "Bauhaus",
        "Color Field Painting",
        "Conceptual Art",
        "Constructivism",
        "Contemporary Realism",
        "Op Art",
        "Photorealism",
        "Pointillism",
        "Precisionism",
        "Tachisme",
        "Orphism",
        "Divisionism",
        "Earthworks",
        "Environmental Art",
        "Geometric Abstraction",
        "Hard-Edge Painting",
        "Installation Art",
        "Kinetic Art",
        "Neo-Expressionism",
        "Performance Art",
        "Post-Minimalism",
        "Stuckism",
        "Suprematism",
        "Vorticism",
        "Art Informel",
        "Neo-Geo",
        "Systems Art",
        "Graffuturism",
        "New Objectivity",
        "Metaphysical Art",
        "Transavantgarde",
        "Post-Painterly Abstraction",
        "Photographic Realism",
        "Dynamic Painting",
        "Ethereal Art",
        "Video Art",
        "Landscapes of the Mind",
        "Figurative Abstraction",
        "Narrative Art",
        "Cynical Realism",
        "New Leipzig School",
        "Hyperrealism",
        "New Casualism",
        "Neo-Pop Art",
        "Pixel Art",
        "Naive Art",
        "Tonalism",
        "Verism",
        "Decollage",
        "Found Art",
        "Installation Art",
        "Video Installation",
        "Concrete Art",
        "Digital Photography",
        "Hard Edge Painting",
        "Aestheticism",
        "Metaphysical Painting",
        "Dark Art",
        "Intimism",
        "Cartooning",
        "Precisionism"
      ],
    artist: [
        "Beeple",
        "Cleon Peterson",
        "James Jean",
        "Hikari Yokoyama",
        "Yoko Honda",
        "Hayao Miyazaki",
        "Oliver Latta (Extraweg)",
        "Erik Jones",
        "Yoko Honda",
        "Yoko Honda",
        "Yoshitaka Amano",
        "Scott Uminga",
        "Rik Oostenbroek",
        "Zarnala",
        "Yoko Honda",
        "Chris B. Murray",
        "Mike Winkelmann (Beeple)",
        "Cinta Vidal",
        "Sebastian Curi",
        "Marco Escobedo",
        "Ines Longevial",
        "Mark Chang",
        "Albert Omoss",
        "Syd Mead",
        "Ian Spriggs",
        "Carnovsky",
        "Tracie Ching",
        "Victo Ngai",
        "Drew Wise",
        "Glenn Brown",
        "Roz Hall",
        "Sachin Teng",
        "Tom Haugomat",
        "Veronique Meignaud",
        "Ed Fairburn",
        "Ana Godis",
        "Chad Wys",
        "Ronan Lynam",
        "Amanda Mocci",
        "Seth Wulsin",
        "Bruno Wagner",
        "Jenny Yu",
        "Davidope",
        "Helena Hauss",
        "Cedric Varcoe",
        "Ania Tomicka",
        "Monica Rohan",
        "Inky Illus",
        "Elliot Schultz",
        "Tim Zarks",
        "Liam Brazier",
        "Cecile Carre",
        "Mary Iverson",
        "Davidope",
        "Simoul Alva",
        "James Lipnickas",
        "Daniel Danger",
        "Sam Rolfes",
        "Christopher Bjerre",
        "Yoshi Sodeoka",
        "Louise Mertens",
        "Gravemind",
        "Phazed",
        "Nicole Guice",
        "Stephanie F. Scholz",
        "Isaiah Sherman",
        "Masashi Wakui",
        "Smithe",
        "Tristan Pigott",
        "Heather McLean",
        "Sam Peacock",
        "James Jean",
        "Maitha Demithan",
        "Ander Niklasson",
        "Andrew Fairclough",
        "Tara McPherson",
        "Pierre Schmidt (Drømsjel)",
        "Harley & J",
        "Eran Fowler",
        "Victor Mosquera",
        "Elicia Edijanto",
        "Gris Grimly",
        "Nagai Hideyuki",
        "Oscar Llorens",
        "Nicolas Ménard",
        "Dorian Legret",
        "Simon Fensholm",
        "Michal Klimczak",
        "Antonio Segura Donat (Dulk)",
        "Koke Núñez Gómez",
        "Lucas David",
        "Tiffany Bozic",
        "Neil Stubbings",
        "Matthew Lyons",
        "Esao Andrews",
      ],
    resolution: [
        "Blurry",
        "Blocky",
        "Fuzzy",
        "Pixelated",
        "Coarse",
        "Grainy",
        "Indistinct",
        "Unfocused",
        "Poor quality",
        "Lack of detail",
        "Low-def",
        "Muddy",
        "Low-res",
        "Gritty",
        "Unclear",
        "Lack of sharpness",
        "Lo-fi",
        "Unrefined",
        "Crude",
        "Jagged edges",
        "Distorted",
        "Artifacts",
        "Underwhelming",
        "Substandard",
        "Imprecise",
        "Unsatisfactory",
        "Low-quality",
        "Diminished detail",
        "Coarseness",
        "Low-fi",
        "Vague",
        "Soft focus",
        "Dull",
        "Aliased",
        "Mistiness",
        "Lack of precision",
        "Rough",
        "Blurred edges",
        "Subpar",
        "Reduced clarity",
        "Hazy",
        "Dim",
        "Inferior quality",
        "Distortion",
        "Lack of definition",
        "Flawed",
        "Muddled",
        "Unpolished",
        "Ultra-high definition",
        "Crystal clear",
        "Razor-sharp",
        "Pin-sharp",
        "Super sharp",
        "Impeccable clarity",
        "Ultra HD",
        "4K",
        "Fine detail",
        "Precision",
        "Crisp",
        "Exquisite",
        "High-quality",
        "Ultra-sharp",
        "Hi-res",
        "Superior resolution",
        "Remarkable detail",
        "Optimal clarity",
        "Unsurpassed sharpness",
        "Fine art quality",
        "Outstanding precision",
        "Exceptional detail",
        "Supreme clarity",
        "Remarkable definition",
        "Immaculate sharpness",
        "Superior quality",
        "Unblemished clarity",
        "Extreme detail",
        "Outstanding resolution",
        "Picture-perfect",
        "Supreme resolution",
        "Precision imaging",
        "Impeccable detail",
        "Top-notch clarity",
        "Flawless sharpness",
        "Unmatched precision",
        "Top-tier resolution",
        "Peerless detail",
        "Unexcelled clarity",
        "Matchless sharpness",
        "Elite quality",
        "Unrivaled resolution",
        "Masterful detail",
        "Top-shelf clarity",
        "Unbeatable sharpness",
        "Prime precision",
        "Perfection",
        "Crystalline clarity",
        "First-rate resolution",
        "Maximum detail"
      ],
    additionalDetails: [
        "Moonlight",
        "Clocks",
        "Shadows",
        "Mirrors",
        "Bridges",
        "Cobblestones",
        "Reflections",
        "Balloons",
        "Banners",
        "Statues",
        "Candles",
        "Birds",
        "Tunnels",
        "Clouds",
        "Rainbows",
        "Stairs",
        "Books",
        "Vines",
        "Streetlights",
        "Lighthouses",
        "Rain",
        "Fog",
        "Ships",
        "Waterfalls",
        "Snow",
        "Fish",
        "Windows",
        "Boats",
        "Music",
        "Stars",
        "Fireflies",
        "Butterflies",
        "Waves",
        "Mountains",
        "People",
        "Horses",
        "Lanterns",
        "Swirls",
        "Portals",
        "Scrolls",
        "Ruins",
        "Flags",
        "Bubbles",
        "Castles",
        "Gears",
        "Hearts",
        "Clockwork",
        "Maps",
        "Dragons",
        "Keys",
        "Arches",
        "Windmills",
        "Crystals",
        "Tornadoes",
        "Doors",
        "Bells",
        "Boulders",
        "Spirals",
        "Columns",
        "Rockets",
        "Constellations",
        "Forests",
        "Galaxies",
        "Water lilies",
        "Holograms",
        "Planets",
        "Whirlpools",
        "Fireworks",
        "Glaciers",
        "Canyons",
        "Dunes",
        "Beaches",
        "Water towers",
        "Umbrellas",
        "Deserts",
        "Hot air balloons",
        "Coral reefs",
        "Jellyfish",
        "Wind turbines",
        "Meteors",
        "Castles in the sky",
        "Zeppelins",
        "Rain clouds",
        "Tornado sirens",
        "Enchanted forests",
        "Floating islands",
        "Underwater caves",
        "Secret passages",
        "Lost cities",
        "Time machines",
        "Ancient scrolls",
        "Hidden treasure",
        "Ancient ruins",
        "Elaborate masks",
        "Greek mythology",
        "Desert oases",
        "City skylines",
        "Abandoned factories",
        "Ancient temples",
        "Futuristic technology"
      ],
    color: [
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Purple",
        "Orange",
        "Pink",
        "Brown",
        "Gray",
        "Black",
        "White",
        "Teal",
        "Lilac",
        "Crimson",
        "Indigo",
        "Gold",
        "Sapphire",
        "Turquoise",
        "Emerald",
        "Ruby",
        "Lavender",
        "Magenta",
        "Sunset Orange",
        "Midnight Blue",
        "Obsidian Black",
        "Pearlescent White",
        "Amethyst Purple",
        "Tropical Sea Green",
        "Molten Lava Red",
        "Electric Lemon Yellow",
        "Exotic Orchid Pink"
      ],
    lighting: [
        "Natural Light",
        "Fluorescent Light",
        "Moonlight",
        "Candlelight",
        "Incandescent Light",
        "LED Light",
        "Halogen Light",
        "Soft Light",
        "Hard Light",
        "Dappled Light",
        "Backlight",
        "Front Light",
        "Rim Light",
        "Key Light",
        "Fill Light",
        "Top Light",
        "Bottom Light",
        "Strip Light",
        "Spotlight",
        "Firelight"
      ]
};

const frozenWords = {}; // Track frozen words

// Function to pick a random word from a category
function getRandomWord(category) {
    const words = categories[category];
    const randomIndex = Math.floor(Math.random() * words.length);
    return words[randomIndex];
}

// Function to generate and display the art description
function generateArtDescription() {
    const artDescription = [];

    for (const category in categories) {
        let word = getRandomWord(category);

        // Check if the word is frozen
        if (frozenWords[category]) {
            word = frozenWords[category];
        }

        const wordElement = document.createElement("span");
        wordElement.textContent = word;
        wordElement.setAttribute("data-category", category);

        if (frozenWords[category]) {
            wordElement.classList.add("frozen");
        }

        wordElement.addEventListener("click", toggleFreeze);
        artDescription.push(wordElement);
    }

    const outputElement = document.getElementById("output");
    outputElement.innerHTML = ""; // Clear the previous content
    artDescription.forEach((element, index) => {
        if (index > 0) {
            outputElement.appendChild(document.createTextNode(", "));
        }
        outputElement.appendChild(element);
    });
}

// Function to freeze/unfreeze a word
function toggleFreeze(event) {
    const wordElement = event.target;
    const category = wordElement.getAttribute("data-category");
    const word = wordElement.textContent;

    if (frozenWords[category] === word) {
        // Unfreeze the word
        delete frozenWords[category];
        wordElement.classList.remove("frozen");
    } else {
        // Freeze the word
        frozenWords[category] = word;
        wordElement.classList.add("frozen");
    }
}

// Event listener for the "Generate" button
document.getElementById("generateButton").addEventListener("click", generateArtDescription);

// Initial generation
generateArtDescription();
